steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/dataform-mfa/dataform-cr-docker/dataform-cr:tag1', '.' ]
images:
- 'europe-west1-docker.pkg.dev/dataform-mfa/dataform-cr-docker/dataform-cr:tag1'
